In [14]:
import pandas as pd
import numpy as np

# Load the dataset
file_path = 'e:/Parth Mca 2nd sem/Data Science/Data Science Assignment/gold_demand_sector.csv'
df = pd.read_csv(file_path)

# Rename columns for easier access
df.columns = ['Sector', '2020', '2021', '2022', '2023', 'Average', 'Extra1', 'Extra2']

# Drop unnecessary columns
df = df.drop(columns=['Extra1', 'Extra2'])

# Remove commas and convert numeric columns to float
for col in ['2020', '2021', '2022', '2023', 'Average']:
    df[col] = df[col].replace({',': ''}, regex=True).astype(float)

# Handle missing values (if any) for numeric columns only
numeric_cols = ['2020', '2021', '2022', '2023', 'Average']
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Display the preprocessed dataset
print(df.head())

                        Sector    2020    2021    2022    2023  Average
0                    Jewellery  1324.0  2231.1  2195.9  2190.5   1985.4
1                   Technology   309.0   337.2   314.8   305.2    316.5
2                   Investment  1794.9   991.5  1112.5   945.3   1211.1
3  Central banks & other inst.   254.9   450.1  1081.9  1049.1    709.0
4                OTC and other  1057.7   694.0    55.7   460.0    566.9


In [15]:
from scipy.stats import zscore

# Detect and remove outliers using Z-score
z_scores = np.abs(df[numeric_cols].apply(zscore))
df = df[(z_scores < 3).all(axis=1)]

In [16]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Calculate precision, recall, and f1-score
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")
print("Confusion Matrix:")
print(conf_matrix)

Precision: 0.0
Recall: 0.0
F1-Score: 0.0
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


e:\Parth Mca 2nd sem\Data Science\Data Science Assignment\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\Parth Mca 2nd sem\Data Science\Data Science Assignment\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
